<!DOCTYPE html>
<html>
<head>
    <title>My Portfolio</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
    <header>
        <h1>My Portfolio</h1>
        <nav>
            <ul>
                <li><a href="home.html">Home</a></li>
                <li><a href="portfolio.html">Portfolio</a></li>
                <li><a href="with AI.html">With AI</a></li>
                <li><a href="about.html">About Me</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="my music.html">my music</a></li>
            </ul>
        </nav>
    </header>
   